-- ============================================================
-- PULZ — Migración de datos desde data.js
-- Ejecutar DESPUÉS de 01_schema.sql en Supabase SQL Editor
-- ============================================================

-- Insertar países
INSERT INTO countries (id, code, name, name_en, name_pt, sort_order) VALUES
  ('argentina', 'AR', 'Argentina', 'Argentina', 'Argentina', 1),
  ('chile', 'CL', 'Chile', 'Chile', 'Chile', 2),
  ('brasil', 'BR', 'Brasil', 'Brazil', 'Brasil', 3),
  ('uruguay', 'UY', 'Uruguay', 'Uruguay', 'Uruguai', 4),
  ('colombia', 'CO', 'Colombia', 'Colombia', 'Colômbia', 5),
  ('peru', 'PE', 'Perú', 'Peru', 'Peru', 6);

-- Argentina (32 carreras)
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Trail Lolog', '2026-01-11', 'argentina', 'Lago Lolog, Neuquén', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Cruce de los Andes', '2026-02-21', 'argentina', 'Bariloche, Río Negro', '{"50K","Ultra","Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('BRUT Bariloche', '2026-03-14', 'argentina', 'Bariloche, Río Negro', '{"50K","33K","21K","10K"}', 'trail', 'https://brut.run/', NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Ushuaia Trail', '2026-02-28', 'argentina', 'Ushuaia, Tierra del Fuego', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Circuito Estaciones (Otoño)', '2026-03-01', 'argentina', 'Buenos Aires, CABA', '{"10K","5K"}', 'road', 'https://www.corro.com.ar/carreras/circuito-de-las-estaciones', NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Women Night Run', '2026-03-07', 'argentina', 'Vicente López, Buenos Aires', '{"8K","3K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Epic Patagonia', '2026-03-14', 'argentina', 'Villa La Angostura, Neuquén', '{"70K","Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K de Carlos Paz', '2026-03-15', 'argentina', 'Villa Carlos Paz, Córdoba', '{"21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('10K Buenos Aires NB', '2026-03-15', 'argentina', 'Palermo, Buenos Aires', '{"10K"}', 'road', 'https://www.newbalance.com.ar', NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K de Mendoza', '2026-03-22', 'argentina', 'Parque Central, Mendoza', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K de Salta', '2026-03-29', 'argentina', 'Salta', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Patagonia Run', '2026-04-08', 'argentina', 'San Martín de los Andes, Neuquén', '{"100Mi","110K","70K","42K","21K","10K"}', 'trail', 'https://patagoniarun.com', 'Una de las carreras de ultra trail más importantes de Sudamérica. Recorrido por bosques patagónicos, lagos cristalinos y senderos de montaña con vistas al volcán Lanín.', 'USD 120 – 280', true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('10K Adidas Supernova', '2026-04-12', 'argentina', 'Vicente López, Buenos Aires', '{"10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Mar del Plata', '2026-04-19', 'argentina', 'Mar del Plata, Buenos Aires', '{"42K","21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K Buenos Aires (FILA)', '2026-04-19', 'argentina', 'Palermo, Buenos Aires', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón Puerto Madryn', '2026-04-26', 'argentina', 'Puerto Madryn, Chubut', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Mendoza', '2026-05-03', 'argentina', 'Mendoza', '{"42K","21K","10K","4K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K de Rosario', '2026-05-10', 'argentina', 'Rosario, Santa Fe', '{"21K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('25K Buenos Aires NB', '2026-05-17', 'argentina', 'Buenos Aires, CABA', '{"25K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón Patria', '2026-05-24', 'argentina', 'Santiago del Estero', '{"42K","21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Fiestas Mayas 10K', '2026-05-25', 'argentina', 'Buenos Aires, CABA', '{"10K","3K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('15K Adidas Adizero', '2026-06-07', 'argentina', 'Buenos Aires, CABA', '{"15K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K de La Plata', '2026-06-14', 'argentina', 'La Plata, Buenos Aires', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón Int. de la Bandera', '2026-06-28', 'argentina', 'Rosario, Santa Fe', '{"42K","10K"}', 'road', 'https://42krosario.com.ar/2026/', NULL, NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('NB 42K Córdoba', '2026-07-05', 'argentina', 'Córdoba', '{"42K","21K","10K","5K"}', 'road', 'https://www.newbalance.com.ar/42k-cordoba-2026/race-series-cordoba-42k.html', NULL, NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('30K Buenos Aires NB', '2026-07-19', 'argentina', 'Buenos Aires, CABA', '{"30K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K de Buenos Aires', '2026-08-23', 'argentina', 'Buenos Aires, CABA', '{"21K"}', 'road', 'https://www.maratondebuenosaires.com/', NULL, NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Buenos Aires', '2026-09-20', 'argentina', 'Buenos Aires, CABA', '{"42K"}', 'road', 'https://www.maratondebuenosaires.com/', 'La maratón más grande de Latinoamérica. Recorre los barrios más emblemáticos de la ciudad con más de 15.000 corredores de todo el mundo.', 'ARS 120 / USD 120', true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('UTACCH Ultra Trail', '2026-10-10', 'argentina', 'Córdoba', '{"15K","26K","55K","85K","120K","165K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('10K San Isidro', '2026-10-25', 'argentina', 'San Isidro, Buenos Aires', '{"10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('10K Night Run', '2026-11-28', 'argentina', 'Buenos Aires, CABA', '{"10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Patagonia Bariloche by UTMB', '2026-11-20', 'argentina', 'Bariloche, Río Negro', '{"130K","86K","50K","25K"}', 'trail', 'https://bariloche.utmb.world/', NULL, NULL, true, 'confirmed', 'pulz', 'approved');

-- Chile (20 carreras)
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Sollipulli Challenge', '2026-02-06', 'chile', 'Melipeuco, Araucanía', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('El Morro Trail Running', '2026-02-07', 'chile', 'Bahía Inglesa, Atacama', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Coya Trail Running', '2026-02-07', 'chile', 'Coya, O''Higgins', '{"21K","10K","5K"}', 'trail', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Desafío Chiloé', '2026-02-14', 'chile', 'Ancud, Los Lagos', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Aguas Andinas Trail Run', '2026-03-01', 'chile', 'Santiago', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('La Gran Travesía', '2026-03-21', 'chile', 'Santiago', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('STGO21K by ASICS', '2026-03-29', 'chile', 'Santiago', '{"21K"}', 'road', 'https://santiago21k.cl/', NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón de Concón', '2026-03-29', 'chile', 'Concón, Valparaíso', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Pampa Perdiz Trail', '2026-04-04', 'chile', 'Alto Hospicio', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Trail Malalcahuello', '2026-04-10', 'chile', 'Araucanía', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Doñihue Trail Race', '2026-04-11', 'chile', 'Doñihue, O''Higgins', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Trail La Fragua', '2026-04-12', 'chile', 'Valparaíso', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Santiago', '2026-04-26', 'chile', 'Santiago', '{"42K","21K","10K"}', 'road', 'https://maratondesantiago.cl/', 'El evento deportivo más masivo de Chile. Miles de corredores recorren las principales avenidas de Santiago con la Cordillera de los Andes como telón de fondo.', 'CLP 25.000 – 49.000', true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Trail del Cañi', '2026-05-01', 'chile', 'Pucón, Araucanía', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Desafío Quillayquén', '2026-05-02', 'chile', 'Coltauco, O''Higgins', '{"Trail"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Torrencial Chile by UTMB', '2026-06-26', 'chile', 'Valdivia, Los Ríos', '{"97K","65K","44K","21K","12K","6K"}', 'trail', 'https://torrencial.utmb.world/', NULL, NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Volcano Marathon', '2026-06-26', 'chile', 'Hanga Roa, Rapa Nui', '{"42K","21K","10K"}', 'road', NULL, NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('STGO21K (2da ed.)', '2026-08-30', 'chile', 'Las Condes, Santiago', '{"21K","10K","5K"}', 'road', 'https://santiago21k.cl/', NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Patagonian Int. Marathon', '2026-09-05', 'chile', 'Torres del Paine, Magallanes', '{"42K","30K","21K","15K","10K"}', 'trail', 'https://www.patagonianinternationalmarathon.com/', NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Ultra Paine', '2026-09-27', 'chile', 'Puerto Natales, Magallanes', '{"80K","50K","42K","35K","21K","14K","7K"}', 'trail', NULL, NULL, NULL, true, 'estimated', 'pulz', 'approved');

-- Brasil (18 carreras)
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Meia Maratona Int. São Paulo', '2026-01-25', 'brasil', 'São Paulo, SP', '{"21K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Trail Brasília', '2026-01-25', 'brasil', 'Brasília, DF', '{"7K","12K","21K","43K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Trail Mar de Minas', '2026-03-07', 'brasil', 'Prados, MG', '{"10K","21K","35K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona Meio do Mundo', '2026-03-14', 'brasil', 'Macapá, AP', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona de Teresina', '2026-03-14', 'brasil', 'Teresina, PI', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona de Manaus', '2026-04-05', 'brasil', 'Manaus, AM', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K Salvador', '2026-04-05', 'brasil', 'Salvador, BA', '{"21K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona Int. São Paulo', '2026-04-12', 'brasil', 'São Paulo, SP', '{"42K","21K","10K","5K"}', 'road', NULL, 'A maior maratona do Brasil. Um percurso icônico pela Avenida Paulista e os principais pontos da megalópole mais vibrante da América do Sul.', NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona de Fortaleza', '2026-04-12', 'brasil', 'Fortaleza, CE', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona de Cascavel', '2026-04-12', 'brasil', 'Cascavel, PR', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Paraty Brazil by UTMB', '2026-05-15', 'brasil', 'Paraty, RJ', '{"108K","58K","35K","25K"}', 'trail', 'https://paraty.utmb.world/', NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona Int. Porto Alegre', '2026-05-31', 'brasil', 'Porto Alegre, RS', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Corrida das Pontes', '2026-06-07', 'brasil', 'Recife, PE', '{"10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Meia de Florianópolis', '2026-06-07', 'brasil', 'Florianópolis, SC', '{"21K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona do Rio de Janeiro', '2026-06-07', 'brasil', 'Rio de Janeiro, RJ', '{"42K","21K","10K","5K"}', 'road', 'https://maratonadorio.com.br/', NULL, NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona FILA', '2026-08-15', 'brasil', 'São Paulo, SP', '{"21K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona Int. de Floripa', '2026-08-30', 'brasil', 'Florianópolis, SC', '{"42K","21K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratona de Niterói', '2026-09-14', 'brasil', 'Niterói, RJ', '{"42K","15K","6K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');

-- Uruguay (7 carreras)
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Ironman 70.3 Punta del Este', '2026-03-15', 'uruguay', 'Punta del Este', '{"Triatlón"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Montevideo', '2026-05-10', 'uruguay', 'Montevideo', '{"42K","21K","10K"}', 'road', 'https://worldsmarathons.com/marathon/maraton-montevideo', NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Half Marathon Montevideo', '2026-08-09', 'uruguay', 'Montevideo', '{"21K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Corre Bosco', '2026-08-16', 'uruguay', 'Montevideo', '{"10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Marathon Punta del Este', '2026-09-06', 'uruguay', 'Punta del Este', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Policía Científica', '2026-09-15', 'uruguay', 'Montevideo', '{"10K","5K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Montevideo 15K', '2026-11-29', 'uruguay', 'Montevideo', '{"15K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');

-- Colombia (23 carreras)
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón del Mar', '2026-02-22', 'colombia', 'Cartagena, Bolívar', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Carrera de las Rosas', '2026-02-22', 'colombia', 'Barranquilla, Atlántico', '{"21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Vuelta Atlética Isla San Andrés', '2026-04-26', 'colombia', 'San Andrés', '{"32K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Corre por los Héroes', '2026-04-26', 'colombia', 'Bogotá D.C.', '{"10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Cali', '2026-05-03', 'colombia', 'Cali, Valle del Cauca', '{"42K","21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Silvia Trail Ancestral', '2026-05-15', 'colombia', 'Silvia, Cauca', '{"42.6K","22.1K","13.2K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('21K Coveñas', '2026-05-17', 'colombia', 'Coveñas, Sucre', '{"21K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Carrera de las Rosas Bogotá', '2026-05-24', 'colombia', 'Bogotá D.C.', '{"15K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón Dulima', '2026-06-07', 'colombia', 'Ibagué, Tolima', '{"42K","21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón Córdoba', '2026-06-07', 'colombia', 'Montería, Córdoba', '{"21K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Chicamocha Canyon Race', '2026-06-15', 'colombia', 'San Gil, Santander', '{"165K","80K","46K","23K","10K"}', 'trail', NULL, NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón Sincelejo', '2026-06-28', 'colombia', 'Sincelejo, Sucre', '{"21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón Cali', '2026-06-28', 'colombia', 'Cali, Valle del Cauca', '{"21K","10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Ultra Valle de Tenza', '2026-07-15', 'colombia', 'Guateque, Boyacá', '{"79K","43K","21K","9K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón de Bogotá', '2026-07-26', 'colombia', 'Bogotá D.C.', '{"21K","10K"}', 'road', 'https://www.mediamaratonbogota.com/', NULL, NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('La Carrera del Pacífico', '2026-08-30', 'colombia', 'Santiago de Cali', '{"10K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón de Medellín', '2026-09-06', 'colombia', 'Medellín, Antioquia', '{"42K","21K","10K","5K"}', 'road', 'https://maratonmedellin.com/', 'La maratón de la ciudad de la eterna primavera. Recorrido urbano a 1.500 msnm con un clima perfecto para correr y una energía única de la gente paisa.', NULL, true, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Carrera de la Mujer', '2026-09-06', 'colombia', 'Bogotá D.C.', '{"10K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Ultra La Mesa', '2026-09-20', 'colombia', 'La Mesa, Cundinamarca', '{"80K","43K","23K","11K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón del Café', '2026-10-04', 'colombia', 'Caldas', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón Valledupar', '2026-10-11', 'colombia', 'Valledupar, Cesar', '{"21K","10K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Frontera Endurance Run', '2026-10-15', 'colombia', 'Jardín, Antioquia', '{"55K","21K","12K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Media Maratón Bucaramanga', '2026-10-18', 'colombia', 'Bucaramanga, Santander', '{"21K","10.5K","5K"}', 'road', NULL, NULL, NULL, false, 'confirmed', 'pulz', 'approved');

-- Perú (9 carreras)
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Santa María 7.5K Run', '2026-01-24', 'peru', 'Santa María del Mar, Lima', '{"7.5K","3K"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Mercedes-Benz Corporate Games', '2026-01-25', 'peru', 'Lima', '{"Corporate"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('IRONMAN 70.3 Perú', '2026-04-26', 'peru', 'Lima', '{"Triatlón"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Wings for Life World Run', '2026-05-10', 'peru', 'Lima', '{"Open"}', 'road', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Maratón adidas Rímac Lima 42K', '2026-05-24', 'peru', 'Lima', '{"42K","21K"}', 'road', 'https://www.running4peru.com/', NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Inca Trail Marathon', '2026-05-24', 'peru', 'Machu Picchu, Cusco', '{"42K","21K","10K"}', 'trail', NULL, 'Corré por los caminos ancestrales incas hasta llegar a una de las Siete Maravillas del Mundo. Trail running a más de 2.400 msnm entre ruinas milenarias y selva nublada.', NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Cordillera Blanca Ultra Trail', '2026-07-02', 'peru', 'Huaraz, Áncash', '{"70K","50K","25K","12K","5K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('KIA Media Maratón de Lima', '2026-08-23', 'peru', 'Lima', '{"21K","10K"}', 'road', 'https://www.running4peru.com/', NULL, NULL, true, 'estimated', 'pulz', 'approved');
INSERT INTO races (name, date, country_id, location, categories, type, website, description, price, is_iconic, status, source, moderation_status) VALUES ('Machu Picchu Trail', '2026-08-24', 'peru', 'Machu Picchu, Cusco', '{"42K","25.7K"}', 'trail', NULL, NULL, NULL, false, 'estimated', 'pulz', 'approved');

-- ============================================================
-- Total: 109 carreras migradas desde data.js
-- ============================================================
